parameters:
    orocrm_call.call.form.type.class: OroCRM\Bundle\CallBundle\Form\Type\CallType
    orocrm_call.call.form.handler.class: OroCRM\Bundle\CallBundle\Form\Handler\CallHandler

services:
    orocrm_call.call.form.type:
        class: %orocrm_call.call.form.type.class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: orocrm_call_form }

    orocrm_call.call.form.handler:
        class: %orocrm_call.call.form.handler.class%
        scope: request
        arguments:
            - @orocrm_call.call.form
            - @request
            - @doctrine.orm.entity_manager

    orocrm_call.call.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_call_call_form"
            - "orocrm_call_form"

