oro_menu_config:
    items:
        activities_tab:
            label: 'orocrm.call.menu.activities_tab.label'
            uri: '#'
            extras:
                icon: icon-puzzle-piece
                position: 30
        call_list:
            label: 'orocrm.call.entity_plural_label'
            route: 'orocrm_call_index'
            extras:
                position: 20
                routes: ['orocrm_call_*']
                description: 'orocrm.call.menu.call_list.description'
        shortcut_call_list:
            label: 'orocrm.call.menu.shortcut_call_list.label'
            route: 'orocrm_call_index'
            extras:
                description: 'orocrm.call.menu.shortcut_call_list.description'

        user_calls_tab:
            label: 'orocrm.call.entity_plural_label'
            extras:
                position: 30
                widgetRoute: 'orocrm_call_widget_calls'
                widgetAcl: 'orocrm_call_view'
                widgetRouteParametersMap:
                    userId: id

        account_calls_tab:
            label: 'orocrm.call.entity_plural_label'
            extras:
                position: 30
                widgetRoute: 'orocrm_call_widget_calls'
                widgetAcl: 'orocrm_call_view'
                widgetRouteParametersMap:
                    accountId: id

        contact_calls_tab:
            label: 'orocrm.call.entity_plural_label'
            extras:
                position: 30
                widgetRoute: 'orocrm_call_widget_calls'
                widgetAcl: 'orocrm_call_view'
                widgetRouteParametersMap:
                    contactId: id

    tree:
        application_menu:
            children:
                activities_tab:
                    children:
                        call_list: ~
        shortcuts:
            children:
                # shortcut_new_call: ~
                shortcut_call_list: ~

        user_activity_tab_panel:
            children:
                user_calls_tab: ~

        account_activity_tab_panel:
            children:
                account_calls_tab: ~

        contact_activity_tab_panel:
            children:
                contact_calls_tab: ~

oro_titles:
    orocrm_call_index: ~
    orocrm_call_update: '%%subject%% - Edit'
    orocrm_call_create: 'Log Call'
