oro_menu_config:
    items:
        call_list:
            label: orocrm.call.entity_plural_label
            route: orocrm_call_index
            extras:
                position: 20
                routes: ['orocrm_call_*']
                description: List of calls
        shortcut_call_list:
            label: Show calls list
            route: orocrm_call_index
            extras:
                description: List of calls

        account_calls_tab:
            label: orocrm.call.entity_plural_label
            extras:
                position: 10
                widgetRoute: orocrm_call_widget_calls
                widget-event: click.tab.data-api

    tree:
        application_menu:
            children:
                customers_tab:
                    children:
                        call_list: ~
        shortcuts:
            children:
                # shortcut_new_call: ~
                shortcut_call_list: ~

        account_activity_tab_panel:
            children:
                account_calls_tab: ~

oro_titles:
    orocrm_call_index: ~
    orocrm_call_update: %%subject%% - Edit
    orocrm_call_create: Log Call
