placeholders:
    view_additional_content_data:
        items:
            orocrm_call_user_calls:
                order: 50

    orocrm_account_action_dropdown:
        items:
            orocrm_account_action_dropdown_add_call: ~

items:
    orocrm_call_user_calls:
        template: OroCRMCallBundle:Call:user_calls.html.twig
        attribute_instance_of: [entity, %oro_user.entity.class%]

    orocrm_account_action_dropdown_add_call:
        template: OroCRMCallBundle:Account:action/logCallButton.html.twig
        order: 40
