parameters:
    orocrm_call.type.call.class: OroCRM\Bundle\CallBundle\Form\Type\CallType

services:
    orocrm_call.form.call:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["orocrm_call", "orocrm_contact", null]
