parameters:
    orocrm_call.call.entity.class:                  OroCRM\Bundle\CallBundle\Entity\Call
    orocrm_call.event_listener.datagrid.call.class: OroCRM\Bundle\CallBundle\EventListener\Datagrid\CallListener
    orocrm_call.activity_list.provider.class: OroCRM\Bundle\CallBundle\Provider\CallActivityListProvider

services:
    orocrm_call.event_listener.datagrid.call:
        class: %orocrm_call.event_listener.datagrid.call.class%
        arguments:
          - @doctrine.orm.entity_manager
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.widget-base-calls-grid, method: onBuildBefore }
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.widget-base-calls-grid, method: onBuildAfter }

    orocrm_call.activity_list.provider:
        class: %orocrm_call.activity_list.provider.class%
        arguments:
           - @oro_entity.doctrine_helper
        tags:
           - {name: oro.activity_list.provider}