parameters:
#    oro_crm_call.example.class: OroCRM\Bundle\CallBundle\Example

services:
#    oro_crm_call.example:
#        class: %oro_crm_call.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
