OroCRM\Bundle\CallBundle\Entity\Call:
    properties:
        subject:
            - NotBlank: ~
            - Length:
                max: 255
        callDateTime:
            - Date: ~
        callStatus:
            - NotBlank: ~
        direction:
            - NotBlank: ~
        contactPhoneNumber:
            - Length:
                max: 255

    constraints:
        - Callback:
            methods: [isPhoneValid]
