workflows:
    # Unqualified Sales Lead Workflow
    order_follow_up:
        label: 'Order Follow Up'
        enabled: true
        type: wizard
        steps:
            not_contacted:
                label: 'Not contacted'
                template: 'OroCRMB2CMockBundle:Workflow:order_follow_up.html.twig'
                order: 10
                allowed_transitions:
                    - send_email
                    - log_call
                view_attributes: [] # TODO: add step view attributes
            emailed:
                label: 'Emailed'
                template: 'OroCRMB2CMockBundle:Workflow:order_follow_up.html.twig'
                order: 20
                allowed_transitions:
                    - log_call
                    - record_feedback
                view_attributes: [] # TODO: add step view attributes
            called:
                label: 'Called'
                template: 'OroCRMB2CMockBundle:Workflow:order_follow_up.html.twig'
                order: 30
                allowed_transitions:
                    - no_reply
                    - record_feedback
                view_attributes: [] # TODO: add step view attributes
            contacted:
                label: 'Contacted'
                template: 'OroCRMB2CMockBundle:Workflow:order_follow_up.html.twig'
                order: 40
                is_final: true
                view_attributes:
                    - { attribute: feedback, view_type: text }
                    # TODO: add step view attributes
        attributes:
            order:
                label: 'Order'
                type: entity
                options:
                    class: OroCRM\Bundle\B2CMockBundle\Entity\SaleOrder
                    managed_entity: true
                    multiple: false
            feedback:
                label: 'Feedback'
                type: string
            # TODO: add required attributes
        transitions:
            send_email:
                label: 'Send Email'
                step_to: emailed
                is_start: true
                frontend_options:
                    icon: 'icon-envelope'
                transition_definition: send_email_definition
                form_options: [] # TODO: add email form
            log_call:
                label: 'Log call'
                step_to: called
                is_start: true
                frontend_options:
                    icon: 'icon-phone'
                transition_definition: log_call_definition
                form_options: [] # TODO: add call form
            no_reply:
                label: 'No reply'
                step_to: not_contacted
                frontend_options:
                    icon: 'icon-repeat'
                transition_definition: no_reply_definition
            record_feedback:
                label: 'Record feedback'
                step_to: contacted
                is_start: true
                frontend_options:
                    icon: 'icon-ok'
                    class: 'btn-primary'
                transition_definition: record_feedback_definition
                form_options:
                    attribute_fields:
                        feedback:
                            form_type: textarea
                            options:
                                required: false
        transition_definitions:
            send_email_definition:
                post_actions: [] # TODO: add send email action
            log_call_definition:
                post_actions: [] # TODO: add create call action
            no_reply_definition:
                post_actions:
                    - @redirect:
                        route: orocrm_b2c_order_view
                        route_parameters:
                            id: $order.id
            record_feedback_definition:
                post_actions:
                    - @redirect:
                        route: orocrm_b2c_order_view
                        route_parameters:
                            id: $order.id
