api:
    entities:
        Oro\Bundle\CallBundle\Entity\Call:
            fields:
                direction:
                    exclude: false # override exclude rule from entity.yml
            filters:
                fields:
                    updatedAt:
                        exclude: false #add updateAt to filters
        Oro\Bundle\CallBundle\Entity\CallDirection:
            exclude: false # override exclude rule from entity.yml
        Oro\Bundle\CallBundle\Entity\CallStatus: ~
